# Generated by Django 3.0.5 on 2026-03-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
